### ISSUE TITLE
docker / centos

### ISSUE THREAD

**Issue by outbackdingo** [subspacecommunity/subspace#11]
running this on docker centos 8 i see 0 ports listening with docker ps ?? i also see 0 ports being provisioned in the instructions, so how does oine get this running on a vm so i can test it. ? maybe more clear instructions are required. As the documents i folloowed dont appear to provide any ports via docker.

**Comment by agonbar** [comment]
When this container is deployed the container is run with:

   cap_add:
    - NET_ADMIN
   network_mode: "host"

This makes the container run directly in the host interface, without mapping, in order to use iptables. This makes docker unable to see what ports are being used. For now, there is no alternative to run the service without this capabilities, so, for example running on a swarm is impossible.

You can try to run it and go to the web interface on the defined port. If it is not working, check that the required kernel modules (modprobe) are running on the host.
