### ISSUE TITLE
Does the resource requirement grow linear with respect to no of users? 

### ISSUE THREAD

**Issue by shaheenkdr** [subspacecommunity/subspace#51]
First of all, finished installing this and tried it. Its incredible. Hats off for the cool work. However, wondering whether the minimum resource of 512 MB ram exceeds as no of users grow ? How many simultaneous connections without dropping the quality can subspace serve at min config ?  The purpose is to pick the lowest AWS node for deployment.

**Comment by jack1902** [comment]
@shaheenkdr Great question, in terms of resource requirement, Subspace itself is there to serve as a portal to download a certificate. This isn't meant to be used by every user all the time, so from subspaces point of view its resource requirements will remain fairly small.

# BUT

^ theres a reason for it being this big. If the number of connections active to `wireguard` at a given point in time is high then it goes without saying that you will need a larger machine. Its difficult to give exact figures.

In terms of running your VPN Instance on AWS, i would be very aware of Data usage. If you are aiming to pull all traffic to the instance in AWS then i would consider using a dedicated server provider who will give you upfront Data usage plans

**Comment by shaheenkdr** [comment]
So are you saying an instance which satisfies minimum requirements with a network bandwidth of 5Gbps should be enough to serve around 10 users simultaneously ?

**Comment by jack1902** [comment]
So this is a question aimed at `wireguard` itself rather than `subspace`. `subspace` is a thin wrapper to `wireguard` to help manage certificates.

As a starting point I'd look at https://www.wireguard.com/performance/ to see if your requirements are met.

I can't say directly because you could have one user who has a SUPER fast connection and is hogging is all the bandwidth on your server when they download a very large file. This would then mean that whilst CPU and RAM requirements are met, Bandwidth is not.

**Comment by shaheenkdr** [comment]
Thanks, that adds more clarity!
